### ISSUE TITLE
telemetry missing if project_name is set

### ISSUE THREAD

**Issue by bastelfreak** [open-telemetry/opentelemetry-ruby#794] opened 2021-06-05 16:28 UTC
Hi people,
I maintain a Rails+sidekiq project where I got a PR that adds opentelemetry support: https://github.com/voxpupuli/vox-pupuli-tasks/pull/272. The following config works fine:

```ruby
# config/application.rb
OpenTelemetry::SDK.configure do |c|
  require 'pg'
  c.use 'OpenTelemetry::Instrumentation::PG'
  c.use 'OpenTelemetry::Instrumentation::Rails'
  c.use 'OpenTelemetry::Instrumentation::Sidekiq'

  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: '127.0.0.1', port: 6831)
    )
  )
end
```

This works fine. jaeger is running from docker with the following docker-compose file:

```yaml
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "14250:14250"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
```

In the jaeger UI, my rails app is listed as unknown_service:

![jaeger](https://user-images.githubusercontent.com/341866/120898489-5c568700-c62b-11eb-817e-63a2480eb5da.jpg)

I also verified that data is coming with `tcpdump -i lo port 6831`

---

Now I saw in your README.md that I can set a version/service name:

```ruby
OpenTelemetry::SDK.configure do |c|
  require 'pg'
  c.use 'OpenTelemetry::Instrumentation::PG'
  c.use 'OpenTelemetry::Instrumentation::Rails'
  c.use 'OpenTelemetry::Instrumentation::Sidekiq'

  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: '127.0.0.1', port: 6831)
    )
  )
  c.service_name = 'vox-pupuli-tasks'
  c.service_version = VERSION
end
```

If I set service_name and/or service_version and restart the app + jaeger, the service doesn't appear in the UI. I did the tcpdump again and didn't saw any packets. Please let me know if you've any clue/need more information.

**Comment by ericmustin** [comment] 2021-06-08 14:23
@bastelfreak Hey there, thanks for reaching out on this. I don't have the jaeger ui running but quickly tried to recreate this using the `Jaeger::CollectorExporter`, but was unable to. See below screenshots, the service name is correctly exported.

I'lll try to carve out some time to see if I can reproduce with the `AgentExporter` although the logic of the Jaeger Encoder ought to be the same. Will update here when I have a chance to do so, should be able to in the next few days.

In the interim, one other idea I wanted to suggest was the use of the `OTEL_RESOURCE_ATTRIBUTES` environment variable to control `service.name` and `service.version` resource attributes ([docs](https://github.com/open-telemetry/opentelemetry-specification/blob/ccbfdd9020ba0d581aa5d880235302f8b0eb8669/specification/sdk-environment-variables.md#general-sdk-configuration)): https://github.com/open-telemetry/opentelemetry-ruby/blob/a9bcbda1ffca0e781e174da7bdaeb1a83394c595/sdk/lib/opentelemetry/sdk/resources/resource.rb#L44

If you try setting the env var like `OTEL_RESOURCE_ATTRIBUTES=service.name=vox-pupuli-tasks,service.version=<VERSION>`, does that resolve the issue for you? Just trying to narrow down why this may not be working as expected for you.

Config: ![config](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/nOuPmrdO/fb92373d-4a10-4a71-936c-966e6add94e0.png?source=client&v=628776a3b77b86b11354ed5f17fda86f)

Output: ![ui-output](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/geug2Jyj/28dca4d5-3a5d-4760-a4da-6c34f471b91f.png?v=a3d18dcea942c4ca820fccd3a6a9d31b)

**Comment by salzig** [comment] 2021-08-16 16:24
Just as a note: seeing similar problems. `Rack` and `ActiveModelSerializers` instrumentation seem to be fine,`Rails` is missing sofar.

**Comment by robertlaurin** [comment] 2021-09-29 13:13
Closing this issue as we were not able to reproduce this.  If some one can confirm this is still an issue and provide a reproduction we can re open the issue and investigate further.

**Closed by robertlaurin** 2021-09-29 13:13 UTC
