### ISSUE TITLE
Mongo instrumentation missing

### ISSUE THREAD

**Issue by genebean** [open-telemetry/opentelemetry-ruby#318] opened 2020-08-14 14:55 UTC
I am working on moving to this library from Datadog's and found that there does not seem to be anything equivalent to https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/mongodb/

**Comment by fbogsany** [comment] 2020-08-14 19:25
Duplicate of #257

**Closed** 2020-08-14 19:25 UTC
