### ISSUE TITLE
Requiring OTLP exporter breaks as of 0.24.1

### ISSUE THREAD

**Issue by jmorrell** [open-telemetry/opentelemetry-ruby#1457] opened 2023-05-31 21:43 UTC
**Description of the bug**

Requiring `"opentelemetry/exporter/otlp"` fails as of the [0.24.1 release](https://github.com/open-telemetry/opentelemetry-ruby/releases/tag/opentelemetry-exporter-otlp%2Fv0.24.1) with an uninitialized constant error:
```
~/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/opentelemetry-exporter-otlp-0.24.1/lib/opentelemetry/exporter/otlp/exporter.rb:38:in `<class:Exporter>': uninitialized constant OpenTelemetry::Exporter::OTLP::VERSION (NameError)
```

**Share details about your runtime**

Operating system details: macOS, Ventura 13.3.1 (a)
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.0"
RUBY_DESCRIPTION: "ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]"

**Share a simplified reproduction if possible**

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "opentelemetry-api"
  gem "opentelemetry-sdk"
  gem "opentelemetry-exporter-otlp"
end

require "opentelemetry-api"
require "opentelemetry-sdk"
require "opentelemetry/exporter/otlp"

OpenTelemetry::SDK.configure do |c|
  c.service_name = "Demo"
end
```

**Comment by jmorrell** [comment] 2023-05-31 21:46
Rolling back to `0.24.0` does not exhibit the same issue

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "opentelemetry-api"
  gem "opentelemetry-sdk"
  gem "opentelemetry-exporter-otlp", "0.24.0"
end

require "opentelemetry-api"
require "opentelemetry-sdk"
require "opentelemetry/exporter/otlp"

OpenTelemetry::SDK.configure do |c|
  c.service_name = "Demo"
end
```

**Comment by leifg** [comment] 2023-05-31 23:20
Same issue

**Comment by jmorrell** [comment] 2023-06-01 04:09
Looks like this was added in https://github.com/open-telemetry/opentelemetry-ruby/pull/1404/files#diff-34fb5aed920b31dca334d76d897e2cd337ee9ac0380b550ee3aef6f5eab60eb5R38 with the `DEFAULT_USER_AGENT` string. This value is set explicitly in the tests: https://github.com/open-telemetry/opentelemetry-ruby/pull/1404/files#diff-de3289c68da25d7cdc56239ec4e726d776221321d148117746d3b8c094dd110aR13

I believe this could be fixed by reversing the require order here so that the version is required first: https://github.com/open-telemetry/opentelemetry-ruby/blob/main/exporter/otlp/lib/opentelemetry/exporter/otlp.rb#L7-L8

**Comment by robertlaurin** [comment] 2023-06-01 21:35
[0.25.0 is released](https://rubygems.org/gems/opentelemetry-exporter-otlp/versions/0.25.0) with a fix.

@jmorrell could you close this once you've confirmed the issue is resolved?

**Comment by jmorrell** [comment] 2023-06-01 21:39
This appears fixed to me. Thank you for the quick merge and new release! 🙌

**Comment by jmorrell** [comment] 2023-06-02 16:21
@robertlaurin Would it be possible to release this also as `0.14.2`? Anyone who depended on `~> 0.14.0` (us) will get a permanently broken version until they bump the version.

**Comment by jmorrell** [comment] 2023-06-05 18:58
or un-publish `0.24.1`?

**Comment by simi** [comment] 2023-06-05 20:21
> or un-publish `0.24.1`?

there is no simple way to un-publish gem and yanking is not really recommended

**Comment by ty-porter** [comment] 2023-07-10 18:03
I understand Ruby 2.7 is EoL but I would like to revisit this.

The latest version of `opentelemetry-exporter-otlp` that supports Ruby 2.7 is `0.24.1` meaning people stuck on that version of Ruby are guaranteed to hit this 

I really think this should be released as `0.24.2` to avoid the problem.

**Comment by robertlaurin** [comment] 2023-07-12 14:10
> I understand Ruby 2.7 is EoL but I would like to revisit this.
> 
> The latest version of `opentelemetry-exporter-otlp` that supports Ruby 2.7 is `0.24.1` meaning people stuck on that version of Ruby are guaranteed to hit this
> 
> I really think this should be released as `0.24.2` to avoid the problem.

I'll re-open the issue until this is addressed properly

**Comment by robertlaurin** [comment] 2023-07-12 23:39
Released here https://rubygems.org/gems/opentelemetry-exporter-otlp/versions/0.24.2

**Comment by ty-porter** [comment] 2023-07-12 23:53
Thank you!

**Comment by robertlaurin** [comment] 2023-07-13 14:12
Thanks for flagging this everyone, going to close the issue now.

**Closed by robertlaurin** 2023-07-13 14:12 UTC
Labels: bug

**Comment by jmorrell** [comment] 2023-07-13 16:21
Thank you!
